# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'NoteSchedule' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'Firebase', '>= 2.5.0'
	pod 'MagicalRecord'
	pod 'Firebase/Database'
	pod 'Firebase/Core'
	pod 'Fabric', '~> 1.7.5'
	pod 'Crashlytics', '~> 3.10.1'
	pod 'Firebase/AdMob'

  # Pods for NoteSchedule

  target 'NoteScheduleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteScheduleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
